# -*- coding: utf-8 -*-
"""video2frames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Wc6hwbJUnp_97UTo_p-EtvXJtsi4LXT
"""

import cv2

file_path_1 = 'background_hand/009/yyc2.mp4'
folder_path = 'background_hand/009'

def videoDetector(cam):  
  image = []
  while True:
    ret, img = cam.read()
    if not ret:
      break
    image.append(img)
  return image

cam1 = cv2.VideoCapture(file_path_1)

imagelist1 = videoDetector(cam1)

for i in imagelist1:
  print(i.shape)
  break

print(len(imagelist1))

startcount = 177
for i, img in enumerate(imagelist1):
  cv2.imwrite(folder_path+'/'+'%05d'%(i+startcount)+'.png',img)


print(startcount + len(imagelist1))